export const BURGER_ADD_ELEM: 'BURGER_ADD_ELEM' = 'BURGER_ADD_ELEM'
export const BURGER_REMOVE_ELEM: 'BURGER_REMOVE_ELEM' = 'BURGER_REMOVE_ELEM'
export const BURGER_MOVE_ELEM: 'BURGER_MOVE_ELEM' = 'BURGER_MOVE_ELEM'
